### ISSUE TITLE
Configuring a subscriber for fanout exchange

### ISSUE THREAD

**Issue by sourabhsriom** [PushyZqin/flask-rabbitmq#1]
Hello Pushy,

Thank you so much for your effort with the flask-rabbitmq library. I am trying to build a flask app which has rabbitmq subscriber running in the background. I tried following the examples that you had provided(consumer) but did not see how we can create a subscriber to a 'fanout' exchange type publisher.

Can you please help give an example of the flask app which has a subscriber of the type I mentioned above?

**Comment by pushyzheng** [comment]
Firstly I am soooo sorry about the delay of my reply.

This library hasn't been in active development for a long time. But it's live once again now. Thank you for your use.

As to the problem your mentioned, I have already fixed it. Now you can simply declare a fanout exchange and bind to queue, like following:

```python
@queue(type=ExchangeType.FANOUT, exchange='fanout_exchange')
def fanout(ch, method, props, body):
    print("fanout queue => {}".format(body))
```

You might notice that there is no queue name. Yes, if you don't assign the queue name, the flask-rabbitmq will declare a temporary queue and bind to fanout exchange automatically.

For more exmaples your can see the [consumer&producer exmaple](https://github.com/PushyZqin/flask-rabbitmq/tree/dev/example), where I have updated code.
